# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ref: <https://megalinter.io/latest/config-file/>

# ----------------------------- Common Variables ----------------------------- #
APPLY_FIXES: all
ENABLE_LINTERS:
  - PYTHON_RUFF
IGNORE_GENERATED_FILES: true
LINTER_RULES_PATH: https://github.com/liblaf/.github/raw/refs/heads/main/.github/linters/
SHOW_ELAPSED_TIME: true
