# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ref: <https://megalinter.io/latest/config-file/>

# ----------------------------- Common Variables ----------------------------- #
IGNORE_GENERATED_FILES: true
ENABLE_LINTERS:
  - REPOSITORY_CHECKOV
LOG_LEVEL: DEBUG
# LINTER_RULES_PATH: https://github.com/liblaf/.github/raw/refs/heads/main/.github/linters/
SHOW_ELAPSED_TIME: true

PYTHON_RUFF_ARGUMENTS:
  - --no-fix
