# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ref: <https://megalinter.io/latest/config-file/>

# ----------------------------- Common Variables ----------------------------- #
IGNORE_GENERATED_FILES: true
LOG_LEVEL: DEBUG
# LINTER_RULES_PATH: https://github.com/liblaf/.github/raw/refs/heads/main/.github/linters/
SHOW_ELAPSED_TIME: true

PYTHON_RUFF_ARGUMENTS:
  - --no-fix
REPOSITORY_CHECKOV_CONFIG_FILE: https://github.com/liblaf/.github/raw/refs/heads/main/.github/linters/.checkov.yml
